name: DeployToQA
on:
  push:
    branches: [  2025qabranch ]
    paths:
            - 'force-app/**'
 
jobs:
  DeltaDeploymentToQA:
    runs-on: [self-hosted, AWS, Node]
    steps:
    - uses: actions/checkout@v2
      with:
        ref: ${{ github.ref }}
        fetch-depth: 0
      if: github.event.action == 'opened' || github.event.action == 'synchronize' || github.event_name == 'push'
    - uses: actions/setup-node@v3
      with:
        node-version: '21'
        #check-latest: true
   
    - name: Install Salesforce CLI
      run: |
        rm -rf node_modules
        npm cache clean --force
        npm install sfdx-cli --legacy-peer-deps
        node_modules/sfdx-cli/bin/run --version
        node_modules/sfdx-cli/bin/run plugins --core
        echo y | node_modules/sfdx-cli/bin/run plugins:install sfdx-git-delta
        
    
    - name: Generate package.xml
      run: |
        #Generate package.xml between the current branch & 
        node_modules/sfdx-cli/bin/run sgd:source:delta --to "HEAD" --from "HEAD~1" --output . -i .gitignore
        echo "--- package.xml generated with added and modified metadata ---"
        cat package/package.xml
    - name: 'Display Username'
      run:
          echo ${{secrets.SFDX_USERNAME_QA02}} | sed 's/./& /g'

    - name: 'Populate auth file with SFDX_URL secret'
      run: 
          'echo ${{ secrets.SFDX_AUTH_URL_QA02}} > token.txt'
      env: 
          SFDX_USE_GENERIC_UNIX_KEYCHAIN: ${{secrets.SFDX_TRUE}}
    

    - name: 'Authenticate against dev hub'
      run:
        node_modules/sfdx-cli/bin/run force:auth:sfdxurl:store -f token.txt -s -a testSandbox
      env: 
          SFDX_USE_GENERIC_UNIX_KEYCHAIN: ${{secrets.SFDX_TRUE}}
                
    - name: Deploy source
      id: Deploy
      #Checking once again before deploying 
      #if: github.event_name == 'pull_request' && github.event.action == 'closed' && github.event.pull_request.merged == true
      run:
        node_modules/sfdx-cli/bin/run force:source:deploy -x package/package.xml -u "$sfdx_username_qa"
      env:
        SFDX_USE_GENERIC_UNIX_KEYCHAIN: ${{secrets.SFDX_TRUE}}
        sfdx_username_qa: ${{secrets.SFDX_USERNAME_QA02}}
